# ah
name: M.H.M.U.
tick: 30
restock: 3600
use_buying_rates: false
use_selling_rates: false

# sql
hostname: 127.0.0.1
database: xidb
username: xi
password: password
port: 3306
fail: true

# Optional external seller persona pool
seller_pool_path: seller_personae.yaml
use_seller_pool_weights: true
